# -*- coding: utf-8 -*-
"""Random_forest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o4F6s_oKsw85ONQw18oinXuc73sXhqfY
"""

import pandas as pd
import numpy as np
from sklearn.datasets import load_digits
digits=load_digits()

dir(digits)

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
plt.gray()
for i in range(4):
  plt.matshow(digits.images[i])

df=pd.DataFrame(digits.data)
df.head()

df.target

df['target']=digits.target
df.head()

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(df.drop(['target'],axis='columns'),df.target,test_size=0.2)

len(X_train)

len(X_test)

from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(X_train,y_train)

model.score(X_test,y_test)

y_predicted=model.predict(X_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_predicted)
cm

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sn
plt.figure(figsize=(10,7))
sn.heatmap(cm,annot=True)
plt.xlabel('Predicted')
plt.ylabel('Truth')